name: dl_project_2021
channels:
  - defaults
  - pytorch
  - rusty1s
  - conda-forge
dependencies:
  - python==3.8.5
  - pip==20.3.3
  - pytorch==1.8.0
  - pytorch-geometric
  - notebook
  - pip:
    - matplotlib==3.3.3
    - numpy==1.19.2
    - scipy==1.5.4
    - scikit-learn==0.24.0
    - tensorboard==2.2.2
    - networkx==2.5
    - python-igraph==0.8.3
    - pycairo==1.20.0
    - pandas==1.3.1